name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Ajuste o nome da branch conforme necessário

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: gh issue --repo ${{ github.repository }} create --title "Issue title" --body "Issue body"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Diretório raiz do seu projeto
